spring.application.name=arena-pernambuco-api
# Banco H2 em arquivo (os dados ficarão salvos na pasta ./data)
spring.datasource.url=jdbc:h2:file:./data/arena-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilita o Console do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
